/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifes.poo2.xadrez.ciu.cih;

import java.awt.Color;

/**
 *
 * @author possatti
 */
public class JPanelCasa extends javax.swing.JPanel {

    private int linha;
    private int coluna;
    private TipoPeca peca;
    private Color corFundo;
    static final private Color corHighlight = Color.YELLOW;

    /**
     * Cria uma casa sem nenhuma das referências necessárias para o
     * funcionamento normal.
     */
    public JPanelCasa() {
        initComponents();
    }

    /**
     * Cria uma casa vazia (i.e. sem peça alguma).
     *
     * @param cor Cor da casa.
     * @param linha Referência da linha no tabuleiro.
     * @param coluna Referência da coluna no tabuleiro.
     */
    public JPanelCasa(Color cor, int linha, int coluna) {
        this();
        this.linha = linha;
        this.coluna = coluna;
        this.corFundo = cor;
        this.peca = null;
    }

    /**
     * Cria uma casa já prenchida com alguma peça em seu interior.
     *
     * @param cor Cor da casa.
     * @param linha Referência da linha no tabuleiro.
     * @param coluna Referência da coluna no tabuleiro.
     * @param peca Tipo da peça que essa casa deve exibir inicialmente.
     */
    public JPanelCasa(Color cor, int linha, int coluna, TipoPeca peca) {
        this(cor, linha, coluna);
        this.peca = peca;
    }

    /**
     * Retira uma peça de dentro da casa e retorna-a.
     *
     * @return Tipo da peça retirada.
     */
    public TipoPeca retirarPeca() {
        TipoPeca pecaRetirada = this.peca;
        this.peca = null;
        atualizarIconePeca();
        return pecaRetirada;
    }

    /**
     * Coloca uma peça dentro desta casa. É importante notar que se já houver
     * alguma peça na casa, ela será substituída.
     *
     * @param novaPeca Peça que será inserida dentro da casa.
     */
    public void colocarPeca(TipoPeca novaPeca) {
        this.peca = novaPeca;
        atualizarIconePeca();
    }

    /**
     * Atualiza o ícone que representa a peça que está contida nesta casa.
     */
    public void atualizarIconePeca() {
        if (peca == null) {
            jLabelPecaIcon.setIcon(null);
        } else {
            jLabelPecaIcon.setIcon(peca.getIcon());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPecaIcon = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPecaIcon)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPecaIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // Coloca a cor de destaque.
        this.setBackground(corHighlight);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(corFundo);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPecaIcon;
    // End of variables declaration//GEN-END:variables
}
