/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.xadrez.ciu.cih;

/**
 *
 * @author possatti
 */
public class JPanelTabuleiro extends javax.swing.JPanel {

    public static final int NUM_LINHAS = 8;
    public static final int NUM_COLUNAS = 8;

    private JPanelCasa casas[][] = new JPanelCasa[NUM_LINHAS][NUM_COLUNAS];

    /**
     * Creates new form JPanelTabuleiro
     */
    public JPanelTabuleiro() {
        initComponents();
        initCasas();
        posicionarPecas();
    }

    /**
     * Posiciona as peças segundo a formação inicial do jogo.
     */
    public void posicionarPecas() {
        // Posiciona peões brancos.
        for (int coluna = 0; coluna < NUM_COLUNAS; coluna++) {
            casas[1][coluna].colocarPeca(TipoPeca.PEAO_BRANCO);
        }

        // Posiciona peões pretos.
        for (int coluna = 0; coluna < NUM_COLUNAS; coluna++) {
            casas[6][coluna].colocarPeca(TipoPeca.PEAO_PRETO);
        }

        // Posiciona outras peças brancas.
        casas[0][0].colocarPeca(TipoPeca.TORRE_BRANCO);
        casas[0][1].colocarPeca(TipoPeca.CAVALO_BRANCO);
        casas[0][2].colocarPeca(TipoPeca.BISPO_BRANCO);
        casas[0][3].colocarPeca(TipoPeca.DAMA_BRANCO);
        casas[0][4].colocarPeca(TipoPeca.REI_BRANCO);
        casas[0][5].colocarPeca(TipoPeca.BISPO_BRANCO);
        casas[0][6].colocarPeca(TipoPeca.CAVALO_BRANCO);
        casas[0][7].colocarPeca(TipoPeca.TORRE_BRANCO);

        // Posiciona outras peças pretas.
        casas[7][0].colocarPeca(TipoPeca.TORRE_PRETO);
        casas[7][1].colocarPeca(TipoPeca.CAVALO_PRETO);
        casas[7][2].colocarPeca(TipoPeca.BISPO_PRETO);
        casas[7][3].colocarPeca(TipoPeca.DAMA_PRETO);
        casas[7][4].colocarPeca(TipoPeca.REI_PRETO);
        casas[7][5].colocarPeca(TipoPeca.BISPO_PRETO);
        casas[7][6].colocarPeca(TipoPeca.CAVALO_PRETO);
        casas[7][7].colocarPeca(TipoPeca.TORRE_PRETO);
    }

    /**
     * Posiciona as casas dentro do tabuleiro.
     */
    private void initCasas() {
        for (int linha = NUM_COLUNAS - 1; linha >= 0; linha--) {
            for (int coluna = 0; coluna < NUM_LINHAS; coluna++) {
                if ((linha + coluna) % 2 == 0) {
                    casas[linha][coluna] = CasaFactory.criarCasaBranca(linha, coluna);
                } else {
                    casas[linha][coluna] = CasaFactory.criarCasaPreta(linha, coluna);
                }
                this.add(casas[linha][coluna]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 0, 0));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
